### ISSUE TITLE
Suggestion for jenkins shared lib testing.

### ISSUE THREAD

**Issue by sblatnick** [department-of-veterans-affairs/codeql-tools#1]
I worked with you @lindluni on the recent pilots.  I mentioned I was working on a shared lib to supplement this one for our needs.

In developing the shared library, I found it cumbersome to have to push for every minor change, so I started looking at how I could test locally without Jenkins.

I have found https://github.com/jenkinsci/JenkinsPipelineUnit to be immensely useful in that effort.  I am suggesting it here for you in case it may be beneficial to your efforts.

**Comment by lindluni** [comment]
This is awesome! I agree, the worst part of this has been having to push and kick off all 20 test pipelines we had for various scenarios. Going to take a look at this and figure out how we can leverage it to reduce our test burden!
