### ISSUE TITLE
Code scanning enablement fails when repository is unarchived

### ISSUE THREAD

**Issue by mcondellva** [department-of-veterans-affairs/codeql-tools#115]
Repositories that have the “Action Required: Configure CodeQL” CodeQL enablement pull request which are then subsequently archived and then unarchived fail.  The configure codeql action fails when trying to create a new pull request.  Two (of 66) repositories that have this issue are VADIR_vsCH33 and VADIR_vsSEP.   An excerpt of the error from the 12/28/2023 run of Configure CodeQL:

[VADIR_vsCH33]: Checking if repository is archived
[VADIR_vsCH33]: Processing repository
[VADIR_vsCH33]: Retrieving .emass-repo-ignore file
[VADIR_vsCH33]: Checking if repository has Code Scanning enabled
[VADIR_vsCH33]: Retrieving repository languages
[VADIR_vsCH33]: Generating CodeQL workflow for supported languages: [java]
[VADIR_vsCH33]: Retrieving SHA for branch master
[VADIR_vsCH33]: Checking if 'ghas-enforcement-codeql' branch exists
[VADIR_vsCH33]: Skipping branch creation as branch already exists
[VADIR_vsCH33]: Checking if '.github/workflows/codeql-analysis.yml' exists
[VADIR_vsCH33]: File already exists, retrieving SHA
[VADIR_vsCH33]: Updating '.github/workflows/codeql-analysis.yml'
[VADIR_vsCH33]: Checking if '.github/emass.json' exists
Warning: [VADIR_vsCH33]: Skipping emass.json creation as file already exists
[VADIR_vsCH33]: Generating pull request body with supported languages: [java]
[VADIR_vsCH33]: Creating CodeQL pull request: https://github.com/department-of-veterans-affairs/VADIR_vsCH33/pulls
Error: [VADIR_vsCH33]: [configuration-failed] Failed to process repository: Error: Failed to create pull request: Validation Failed: {"resource":"PullRequest","code":"custom","message":"A pull request already exists for department-of-veterans-affairs:ghas-enforcement-codeql."}

**Comment by lindluni** [comment]
Thanks @mcondellva 

I will take a look at this!

**Comment by lindluni** [comment]
I have a fix here: https://github.com/department-of-veterans-affairs/codeql-tools/commit/a5cde80d47d4018582273a54333bf670576f5524

I just need to wait until Monday when I get back from holiday travel to test the change, as I don't have my access to my non-production credentials. But should have it merged on Tuesday.
