### ISSUE TITLE
rename of output artifact has broken downstream verifications

### ISSUE THREAD

**Issue by lbenhartVA** [department-of-veterans-affairs/codeql-tools#128]
We have several verification processes which have now broken as a result of the renaming of the output file
name: codeql-scan-results-${{ inputs.language }}-${{ github.job }}

This was checked in as part of https://github.com/department-of-veterans-affairs/codeql-tools/pull/125/

**Comment by lindluni** [comment]
We've reverted that change, instead we will instruct users with mono-repos to make changes instead. Note the sentiment still stands about this repository's actions being deprecated, but you may continue to use them.

**Comment by lbenhartVA** [comment]
good to know about the deprecated actions, I was not aware ... I guess I have to read up on that as well
