### ISSUE TITLE
department-of-veterans-affairs/codeql-tools/codeql-analysis fails with "process the submitted SARIF file"

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/codeql-tools#45]
Hello-

One of our repos had an automated PR added to it asking to enable OIT's CodeQL analysis tool: https://github.com/department-of-veterans-affairs/next-build/pull/116

I spoke to OIT OIS Software Assurance to get help with determining our values for emass.json. Once those were found, I went ahead and added them and the workflow attempted to run. However it fails consistently with the error:

> Error: Code Scanning could not process the submitted SARIF file:
> CodeQL analyses from advanced configurations cannot be processed when the default setup is enabled

This is a link to a workflow run with debugging enabled: https://github.com/department-of-veterans-affairs/next-build/actions/runs/5624972334/job/15242935908

I've also attached text of the run log in case that's useful.

If there's something wrong with our configuration, we'd appreciate help figuring that out. Thank you!

-Tim Cosgrove
Veterans-Facing Services Platform-Va.gov
tim.cosgrove@agile6.com or timothy.cosgrove1@va.gov

**Comment by lindluni** [comment]
Hi @timcosgrove 

This repo had default code scanning enabled on this page under the `Code Scanning` section: https://github.com/department-of-veterans-affairs/next-build/settings/security_analysis

I’ve gone ahead and disabled that and retriggered the job in the PR and it passed. You cannot have default code scanning enabled and advanced code scanning (where you define the scan in a file) at the same time.

You should be good to go now
