### ISSUE TITLE
Not set & invalid emass.json settings not causing code health indicator to report a problem

### ISSUE THREAD

**Issue by Boberski** [department-of-veterans-affairs/codeql-tools#55]
During a support call this afternoon for `https://github.com/department-of-veterans-affairs/ves-redis-lookup-sync-svc`

We noticed that in their `emass.json` file, they had not updated the default system ID, and also had an invalid system name

However, after they had done the other necessary configuration, the code health indicator was green, no problems

While the repo is correctly flagged on the enablement dashboard as there being a problem, and e.g. the error issue is fine,

.. I had thought that invalid `emass.json` data (invalid system ID) also caused the tool health check to fail?

**Comment by lindluni** [comment]
Addressed in https://github.com/department-of-veterans-affairs/codeql-tools/commit/457ba95d557b92f745d4535407af5abb2affb2b4
