### ISSUE TITLE
Metrics dashboard not honoring excluded_languages

### ISSUE THREAD

**Issue by mcondellva** [department-of-veterans-affairs/codeql-tools#65]
The missing analysis/database column of the metrics dashboard appears to include languages that have been excluded in the codeql.yml configuration file.

For example, see the repository: https://github.com/department-of-veterans-affairs/htr-trmUpgrade.
They appropriately exclude the language `cpp` in https://github.com/department-of-veterans-affairs/htr-trmUpgrade/blob/Core_Build_Branch/.github/codeql.yml. It looks to be specified correctly and last night’s verify-scan run didn’t flag any issues, however in the metrics dashboard `cpp` shows up under the missing analysis/missing database columns.

At a quick glance, there seems to be some other examples:
- https://github.com/department-of-veterans-affairs/epsi-resources
- https://github.com/department-of-veterans-affairs/epsi-vistalink-service

**Comment by lindluni** [comment]
Fixed in: https://github.com/department-of-veterans-affairs/codeql-tools/commit/4db31ee94a0538c70950fda1b568437687ccdaea
